# Generated by Django 4.2.7 on 2023-12-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorProducts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precio',
        ),
    ]
