# Generated by Django 4.2.7 on 2023-12-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorProducts', '0002_remove_productos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
